on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check-notest

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04, r: '3.0'}
          - {os: ubuntu-16.04, r: '3.1'}
          - {os: ubuntu-16.04, r: '3.2'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Build
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: R CMD build .

      - name: Check
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
        run: R CMD check --ignore-vignettes --no-manual groundhog_*.tar.gz
